### PR TITLE
Add logos

### PR DESCRIPTION
**Pull request by btuttle**
Adding Canopius and Brach to the customer logos

I was bored and took a stab at adding this, someone make sure I didn't overlook anything, thanks.

### CODE REVIEW

**Comment by BenjaminRichardson** [comment]
Added small tweak for image wrapping on large screens 
Was:
Screen Shot 2020-02-19 at 1 14 00 PM
Now:
Screen Shot 2020-02-19 at 1 49 32 PM

**Review by BenjaminRichardson — APPROVED** [review]
Looks good!

**Review by RyanRutkin — APPROVED** [review]
Looks good to me!

**Comment by btuttle** [comment]
Thanks gents!

**Pull request merged**
